### PR TITLE
feat: Log JSON format

### PR DESCRIPTION
**Pull request by dumebi**
#### What does this PR do
Implemented `InitJson()` and `LogJson`, to initialize and log errors in JSON format

#### How should this be manually tested
run `go run example/json.go` twice

#### Any background context you want to add
I think you'll write how it works

### CODE REVIEW

**Comment by dumebi** [comment]
#### What does this PR do
Implemented `InitJson()` and `LogJson`, to initialize and log errors in JSON format

#### Description of Task to be completed

#### How should this be manually tested
run `go run example/json.go` twice

#### Any background context you want to add

#### Screenshots

**Review by Thecarisma — COMMENTED** [review]
For JSON the time stamp should be in Unix time. JSON result might be sent to another location so Unix time will preserve the actual time and can be easily formatted to another time zone.

**Comment by dumebi** [comment]
Yeah, i realized that. i think that's something that should be done in the log file as well @ichtrojan

**Comment by Thecarisma** [comment]
The date format is proper for file logging since the log file is expected to show the detail of the error. Also, the Init() method should not explicitly accept the file type parameter, the method `LogJson()` should know to log JSON in the file regardless of what is in the file before.

**Pull request merged**
